import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // Match the repo's previous Prettier print width.
    printWidth: 80,
    ignorePatterns: [
      // Mustache tag names in plop templates break Oxfmt's Handlebars parser.
      "**/*.hbs",
      // Generated by `wrangler types`.
      "packages/kumo-screenshot-worker/worker-configuration.d.ts",
      // TEMPORARY Prettier-parity scope; lifted in the follow-up formatting PR.
      "**/*.mdx",
      "**/*.yml",
      "**/*.jsonc",
      // Oxfmt diffs from Prettier on long CSS lines: https://github.com/oxc-project/oxc/issues/24843
      "packages/kumo/src/styles/kumo.css",
      // TEMPORARY: Oxfmt doesn't follow Prettier 3.9's union wrapping yet: https://github.com/oxc-project/oxc/issues/23923
      "packages/kumo-docs-astro/src/components/demos/Chart/ColorDemo.tsx",
      "packages/kumo-figma/src/generators/shared.ts",
      "packages/kumo-figma/src/parsers/tailwind-to-figma.ts",
      "packages/kumo/src/components/chart/Color.ts",
      "packages/kumo/src/components/dialog/dialog.tsx",
      "packages/kumo/src/components/toast/toast.tsx",
      "packages/kumo/src/utils/portal-provider.tsx",
      "packages/kumo/src/utils/resolve-variant.ts",
      "tools/deployments/validate-pr-description.ts",
    ],
    // Replaces prettier-plugin-tailwindcss; the stylesheet teaches kumo-* utilities.
    sortTailwindcss: {
      functions: ["cn", "clsx"],
      stylesheet: "./packages/kumo/src/styles/kumo-standalone.css",
    },
  },
  lint: {
    // Unlinted legacy scripts; they import kumo's non-exported files.
    ignorePatterns: ["packages/kumo-figma/scripts/**"],
    jsPlugins: [
      "./packages/kumo/lint/kumo-plugin.js",
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
    plugins: ["eslint", "typescript"],
    categories: {
      correctness: "error",
    },
    rules: {
      "kumo/no-cross-package-imports": "error",
      "kumo/no-primitive-colors": "error",
      "kumo/no-tailwind-dark-variant": "error",
      "kumo/no-flow-node-custom-render": "error",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
  },
});
